export const ADD_COMBATANT = 'ADD_COMBATANT';
export const UPDATE_COMBATANT = 'UPDATE_COMBATANT';
export const SORT_COMBATANTS = 'SORT_COMBATANTS';
export const UPDATE_CURRENT_TURN = 'UPDATE_CURRENT_TURN';
